POST http://localhost:3000/api/paginas HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbWVyY2lvc1BlcGVAZ21haWwuY29tIiwicm9sIjoiY29tZXJjaW8iLCJpYXQiOjE2ODM3MDg5MDEsImV4cCI6MTcxNTI0NDkwMX0.usEVxMciR7CxEsXP3cy1CBiOIG-OD3EjUd0UGldPvXM

{
    "titulo":"Deportes-Madrid",
    "ciudad":"Madrid",
    "actividad":"Deportes",
    "resumen":"Deportes Madrid ven a vernos",
    "textos":["Hola","Hola","Hola","Hola","Hola","Hola"],
    "fotos":["Hola.img","Hola.img","Hola.img","Hola.img","Hola.img","Hola.img"],
    "reseñas":[{"puntuacion":4,"comentario":"Me parece muy guay"}]
}
###
PUT http://localhost:3000/api/paginas HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbWVyY2lvc1BlcGVAZ21haWwuY29tIiwicm9sIjoiY29tZXJjaW8iLCJpYXQiOjE2ODM3MDg5MDEsImV4cCI6MTcxNTI0NDkwMX0.usEVxMciR7CxEsXP3cy1CBiOIG-OD3EjUd0UGldPvXM

{
    "ciudad":"Gerona",
    "actividad":"Deportes Riesgo" 
}

###

GET http://localhost:3000/api/paginas HTTP/1.1


###

GET http://localhost:3000/api/paginas/Deportes-Madrid HTTP/1.1


###

DELETE http://localhost:3000/api/paginas HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbWVyY2lvc1BlcGVAZ21haWwuY29tIiwicm9sIjoiY29tZXJjaW8iLCJpYXQiOjE2ODM3MDg5MDEsImV4cCI6MTcxNTI0NDkwMX0.usEVxMciR7CxEsXP3cy1CBiOIG-OD3EjUd0UGldPvXM

###
POST http://localhost:3000/api/paginas/foto HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbWVyY2lvc1BlcGVAZ21haWwuY29tIiwicm9sIjoiY29tZXJjaW8iLCJpYXQiOjE2ODM3MDg5MDEsImV4cCI6MTcxNTI0NDkwMX0.usEVxMciR7CxEsXP3cy1CBiOIG-OD3EjUd0UGldPvXM

--Boundry
Content-Disposition: form-data; name="image"; filename="esp.png"
Content-Type: image/png

< ./esp.png
--Boundry--
###
PUT http://localhost:3000/api/paginas/foto/1 HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbWVyY2lvc1BlcGVAZ21haWwuY29tIiwicm9sIjoiY29tZXJjaW8iLCJpYXQiOjE2ODM3MDg5MDEsImV4cCI6MTcxNTI0NDkwMX0.usEVxMciR7CxEsXP3cy1CBiOIG-OD3EjUd0UGldPvXM

--Boundry
Content-Disposition: form-data; name="image"; filename="esp.png"
Content-Type: image/png

< ./esp.png
--Boundry--
###
POST http://localhost:3000/api/paginas/texto HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbWVyY2lvc1BlcGVAZ21haWwuY29tIiwicm9sIjoiY29tZXJjaW8iLCJpYXQiOjE2ODM3MDg5MDEsImV4cCI6MTcxNTI0NDkwMX0.usEVxMciR7CxEsXP3cy1CBiOIG-OD3EjUd0UGldPvXM

{    
    "texto":"Hola buenas tardes"
}

###
PUT http://localhost:3000/api/paginas/texto/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbWVyY2lvc1BlcGVAZ21haWwuY29tIiwicm9sIjoiY29tZXJjaW8iLCJpYXQiOjE2ODM3MDg5MDEsImV4cCI6MTcxNTI0NDkwMX0.usEVxMciR7CxEsXP3cy1CBiOIG-OD3EjUd0UGldPvXM

{    
    "texto":"Hola buenas pepe"
}

###

GET http://localhost:3000/api/paginas/buscar/Barelona/ HTTP/1.1


###

PATCH http://localhost:3000/api/paginas/Deportes-Madrid HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsZXhAZ21haWwuY29tIiwicm9sIjoidXN1YXJpb19yZWdpc3RyYWRvIiwiaWF0IjoxNjgzNTY0NzY1LCJleHAiOjE3MTUxMDA3NjV9.y1HOzIe95IkKAhXiQ-vMfJNnK23Lm73WVfbQnxgEFFQ

{
    "reseña":{
            "puntuacion":2,
            "comentario":"Me parece muy guay!!!!"
    }
}